# Generated by Django 5.1.2 on 2026-01-13 06:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Memo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("subject", models.CharField(max_length=500)),
                (
                    "content",
                    models.TextField(help_text="Rich text content of the memo"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "Normal"), ("urgent", "Urgent")],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "current_stage",
                    models.IntegerField(
                        default=1, help_text="1=Draft, 2=Review, 3=Approval"
                    ),
                ),
                ("yearly_serial", models.PositiveIntegerField(blank=True, null=True)),
                ("serial_year", models.IntegerField(blank=True, null=True)),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="True when submitted for approval, prevents editing",
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "final_approver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Director/MD for final approval",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memos_to_approve",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        help_text="Person who created the memo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_memos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "through_cc",
                    models.ForeignKey(
                        blank=True,
                        help_text="General Manager (for notification only, not approval)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memos_ccd",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_unit_head",
                    models.ForeignKey(
                        help_text="Unit Head who will review the memo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memos_to_review",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Memo",
                "verbose_name_plural": "Memos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemoApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.IntegerField(
                        choices=[
                            (1, "Draft"),
                            (2, "Review (Unit Head)"),
                            (3, "Approval (Director/MD)"),
                        ]
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("returned", "Returned for Revision"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Approval/rejection comments"
                    ),
                ),
                ("action_date", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memo_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "memo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="memo.memo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Memo Approval",
                "verbose_name_plural": "Memo Approvals",
                "ordering": ["-action_date"],
            },
        ),
        migrations.CreateModel(
            name="MemoAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="memo_attachments/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "txt",
                                ]
                            )
                        ],
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                ("file_type", models.CharField(help_text="MIME type", max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "memo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="memo.memo",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_memo_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Memo Attachment",
                "verbose_name_plural": "Memo Attachments",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="memo",
            index=models.Index(
                fields=["reference_number"], name="memo_memo_referen_f18773_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memo",
            index=models.Index(
                fields=["status", "created_at"], name="memo_memo_status_bd42d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memo",
            index=models.Index(
                fields=["initiator", "status"], name="memo_memo_initiat_7a7ecd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memoapproval",
            index=models.Index(
                fields=["memo", "stage"], name="memo_memoap_memo_id_da4aa4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memoapproval",
            index=models.Index(
                fields=["actor", "action_date"], name="memo_memoap_actor_i_d48fd1_idx"
            ),
        ),
    ]
