# Generated by Django 5.1.2 on 2026-01-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("director", "Director"),
                    ("hr_manager", "HR Manager"),
                    ("general_staff", "General Staff"),
                ],
                default="general_staff",
                max_length=20,
            ),
        ),
    ]
