# Generated by Django 5.1.2 on 2026-01-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_customuser_bio_customuser_date_joined_org_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="username", max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
