# Generated by Django 5.1.2 on 2026-01-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
    ]
