# Generated by Django 5.1.2 on 2026-01-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_customuser_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="parent",
        ),
    ]
