# Generated by Django 5.1.2 on 2026-01-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_department_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
