# Generated by Django 5.1.2 on 2026-01-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_customuser_profile_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="admin_invite_accepted",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="admin_invite_sent",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="ibank_onboarded",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_buyer",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_merchant",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_seller",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="kyc_completed",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="office_extension",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="reports_to",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="send_app_notifications",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="send_email_notifications",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="send_sms_notifications",
        ),
        migrations.RemoveField(
            model_name="department",
            name="code",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
