# Generated by Django 5.1.2 on 2026-01-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_remove_customuser_admin_invite_accepted_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StaffTask",
        ),
    ]
