# Generated by Django 5.1.2 on 2026-01-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_delete_stafftask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="position",
        ),
    ]
