# Generated by Django 5.1.2 on 2026-01-14 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_remove_customuser_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("SIDEBAR", "Sidebar"),
                            ("OVERVIEW", "Overview"),
                            ("USER", "User"),
                            ("USER_KYC", "User Kyc"),
                            ("TRANSACTION", "Transaction"),
                            ("WEBHOOK", "Webhook"),
                            ("DISPUTE", "Dispute"),
                            ("MERCHANT", "Merchant"),
                            ("SETTINGS", "Settings"),
                            ("CMS", "Cms"),
                            ("EVENT", "Event"),
                            ("REFERRER", "Referrer"),
                            ("EMAIL_PROVIDER", "Email Provider"),
                            ("PAYMENT_GATEWAY", "Payment Gateway"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["module", "name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="user.role",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(related_name="roles", to="user.permission"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
