# Generated by Django 5.1.2 on 2026-01-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_permission_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
        migrations.AlterField(
            model_name="permission",
            name="module",
            field=models.CharField(
                choices=[
                    ("SIDEBAR", "Sidebar"),
                    ("OVERVIEW", "Overview"),
                    ("USER", "User"),
                    ("SETTINGS", "Settings"),
                    ("CORRESPONDENCE", "Correspondence"),
                    ("MEMO", "Memo"),
                    ("LEAVE", "Leave"),
                    ("RECRUITMENT", "Recruitment"),
                ],
                max_length=50,
            ),
        ),
    ]
