# Generated by Django 5.1.2 on 2026-01-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('SIDEBAR', 'Sidebar'), ('OVERVIEW', 'Overview'), ('USER', 'User'), ('SETTINGS', 'Settings'), ('CORRESPONDENCE', 'Correspondence'), ('MEMO', 'Memo'), ('LEAVE', 'Leave'), ('RECRUITMENT', 'Recruitment'), ('HR_CONFIG', 'Hr Config')], max_length=50),
        ),
    ]
