# Generated by Django 5.1.2 on 2026-01-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="module",
            field=models.CharField(
                choices=[
                    ("SIDEBAR", "Sidebar"),
                    ("OVERVIEW", "Overview"),
                    ("SETTINGS", "Settings"),
                    ("CORRESPONDENCE", "Correspondence"),
                    ("HR", "Hr"),
                    ("EXECUTIVE", "Executive"),
                    ("TASKS", "Tasks"),
                ],
                max_length=50,
            ),
        ),
    ]