# Generated by Django 5.1.2 on 2026-01-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_permission_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="module",
            field=models.CharField(
                choices=[
                    ("DASHBOARD", "Dashboard"),
                    ("HR_SETTINGS", "Hr Settings"),
                    ("TASKS", "Tasks"),
                    ("CORRESPONDENCE", "Correspondence"),
                    ("APPROVALS", "Approvals"),
                    ("PERFORMANCE_OVERVIEW", "Performance Overview"),
                    ("ROLES", "Roles"),
                    ("SYSTEM_CONFIG", "System Config"),
                    ("DEPARTMENTS", "Departments"),
                ],
                max_length=50,
            ),
        ),
    ]
