# Generated by Django 5.1.2 on 2026-01-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_alter_permission_module"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staffactivity",
            old_name="approvals_given",
            new_name="approvals_pending",
        ),
        migrations.RemoveField(
            model_name="performancerecord",
            name="approvals_given",
        ),
        migrations.RemoveField(
            model_name="performancerecord",
            name="approvals_pending",
        ),
        migrations.RemoveField(
            model_name="performancerecord",
            name="avg_approval_time_hours",
        ),
        migrations.RemoveField(
            model_name="performancerecord",
            name="department_rank",
        ),
        migrations.RemoveField(
            model_name="performancerecord",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="performancerecord",
            name="overall_rank",
        ),
        migrations.RemoveField(
            model_name="staffactivity",
            name="tasks_completed",
        ),
    ]
