# Generated by Django 5.1.2 on 2026-01-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "user",
            "0016_rename_approvals_given_staffactivity_approvals_pending_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="performancerecord",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Performance Record",
                "verbose_name_plural": "Performance Records",
            },
        ),
        migrations.AlterUniqueTogether(
            name="performancerecord",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="performancerecord",
            name="month",
        ),
    ]
