# Generated by Django 5.1.2 on 2026-02-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_alter_customuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
