# Generated by Django 5.1.2 on 2026-02-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_remove_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="create_once",
            field=models.BooleanField(default=True),
        ),
    ]
