# Generated by Django 5.1.2 on 2026-01-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="approval",
            name="department",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
    ]
