# Generated by Django 5.1.2 on 2026-01-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Correspondence",
        ),
        migrations.RemoveField(
            model_name="memo",
            name="author",
        ),
        migrations.RemoveField(
            model_name="memo",
            name="department",
        ),
        migrations.RemoveField(
            model_name="memo",
            name="recipients",
        ),
        migrations.DeleteModel(
            name="DepartmentPerformance",
        ),
        migrations.DeleteModel(
            name="Memo",
        ),
    ]
