# Generated by Django 5.1.2 on 2026-01-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_remove_approval_department_delete_department"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
