# Generated by Django 5.1.2 on 2026-01-17 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0014_alter_permission_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(default='Default Leave Approval', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_approve_threshold_days', models.IntegerField(default=2, help_text='Auto-approve leave requests less than this many days')),
                ('enable_auto_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Approval Workflow',
                'verbose_name_plural': 'Leave Approval Workflows',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('allowance_days', models.DecimalField(decimal_places=2, help_text='Total days allowed (e.g., 30 for annual, 90 for maternity)', max_digits=5)),
                ('accrual_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('per_event', 'Per Event')], default='yearly', help_text='How the allowance accrues', max_length=20)),
                ('accrual_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Days accrued per period (e.g., 2.5 days/month for annual leave)', max_digits=5, null=True)),
                ('requires_documentation', models.BooleanField(default=False, help_text='Whether this leave type requires supporting documents')),
                ('is_paid', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('color_code', models.CharField(default='#3B82F6', help_text='Hex color for calendar display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['leave_type_name'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(editable=False, help_text='Auto-generated e.g., APP-2024-001', max_length=50, unique=True)),
                ('template_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('template_content', models.JSONField(default=dict, help_text='Structured template with sections, questions, and KPIs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appraisal_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appraisal Template',
                'verbose_name_plural': 'Appraisal Templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start_time', models.TimeField(default='09:00', help_text='Default shift start time (e.g., 09:00)')),
                ('shift_end_time', models.TimeField(default='17:00', help_text='Default shift end time (e.g., 17:00)')),
                ('late_grace_period_minutes', models.IntegerField(default=15, help_text='Minutes allowed after shift start before marked late')),
                ('enable_overtime', models.BooleanField(default=True, help_text='Whether overtime tracking is enabled')),
                ('overtime_threshold_minutes', models.IntegerField(default=30, help_text='Minutes after shift end to qualify as overtime')),
                ('working_days_per_week', models.IntegerField(default=5, help_text='Number of working days per week')),
                ('working_days', models.JSONField(default=list, help_text="Array of working days: ['monday', 'tuesday', etc.]")),
                ('require_check_in', models.BooleanField(default=True)),
                ('require_check_out', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_policy_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Policy',
                'verbose_name_plural': 'Attendance Policy',
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('year', models.IntegerField(editable=False)),
                ('holiday_type', models.CharField(choices=[('official', 'Official Holiday'), ('observance', 'Observance'), ('restricted', 'Restricted Holiday')], default='official', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether this holiday repeats annually on the same date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public Holiday',
                'verbose_name_plural': 'Public Holidays',
                'ordering': ['date'],
                'unique_together': {('holiday_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeaveApprovalStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_order', models.IntegerField(help_text='Order of this stage in workflow (1, 2, 3, etc.)')),
                ('stage_name', models.CharField(max_length=100)),
                ('approver_type', models.CharField(choices=[('initiator', 'Staff Member (Initiator)'), ('direct_manager', 'Direct Manager'), ('hr_admin', 'HR Admin'), ('department_head', 'Department Head'), ('ceo', 'CEO/Executive')], max_length=30)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this stage is mandatory')),
                ('can_skip', models.BooleanField(default=False, help_text='Whether this stage can be skipped under certain conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_role', models.ForeignKey(blank=True, help_text='Specific role required to approve at this stage', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.role')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='hr_config.leaveapprovalworkflow')),
            ],
            options={
                'verbose_name': 'Leave Approval Stage',
                'verbose_name_plural': 'Leave Approval Stages',
                'ordering': ['workflow', 'stage_order'],
                'unique_together': {('workflow', 'stage_order')},
            },
        ),
    ]
