# Generated by Django 5.1.2 on 2026-01-10 21:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audit_module",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication"),
                            ("user", "User Management"),
                            ("audit", "Audit Trail"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("admin_login", "Admin Login"),
                            ("invite_user", "Invited User"),
                            ("deactivate_user", "Deactivated User"),
                            ("activate_user", "Activated User"),
                            ("restrict_user", "Restricted User"),
                            ("unrestrict_user", "Unrestricted User"),
                            ("remove_admin_user", "Removed Admin User"),
                            ("update_admin_user", "Updated Admin User"),
                            ("manual_debit_user", "Manually Debited User"),
                            ("manual_credit_user", "Manually Credited User"),
                            ("convert_user_type", "Converted User Type"),
                            ("view_correspondence", "Viewed Correspondence"),
                            (
                                "change_correspondence_status",
                                "Changed Correspondence Status",
                            ),
                            ("archive_correspondence", "Archived Correspondence"),
                            ("add_new_blog", "Added New Blog"),
                            ("edit_blog", "Edited Blog"),
                            ("save_as_draft", "Saved Blog as Draft"),
                            ("delete_blog", "Deleted Blog"),
                            ("permanently_delete_blog", "Permanently Deleted Blog"),
                            ("restore_blog", "Restored Blog"),
                        ],
                        db_index=True,
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("pending", "Pending"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("user_name", models.CharField(max_length=255)),
                ("user_role", models.CharField(max_length=255)),
                ("user_email", models.EmailField(db_index=True, max_length=254)),
                ("action", models.TextField()),
                ("request_meta", models.JSONField(blank=True, null=True)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique request ID to trace log entries across systems/logs",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
