# Generated by Django 5.1.2 on 2026-01-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditlog_audit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="audit_module",
            field=models.CharField(
                choices=[
                    ("auth", "Authentication"),
                    ("user", "User Management"),
                    ("audit", "Audit Trail"),
                    ("memo", "Memo Management"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="audit_type",
            field=models.CharField(
                choices=[
                    ("admin_login", "Admin Login"),
                    ("invite_user", "Invited User"),
                    ("deactivate_user", "Deactivated User"),
                    ("approve_user", "Approved User"),
                    ("restrict_user", "Restricted User"),
                    ("unrestrict_user", "Unrestricted User"),
                    ("remove_admin_user", "Removed Admin User"),
                    ("update_admin_user", "Updated Admin User"),
                    ("manual_debit_user", "Manually Debited User"),
                    ("manual_credit_user", "Manually Credited User"),
                    ("convert_user_type", "Converted User Type"),
                    ("view_correspondence", "Viewed Correspondence"),
                    ("change_correspondence_status", "Changed Correspondence Status"),
                    ("archive_correspondence", "Archived Correspondence"),
                    ("create_memo", "Created Memo"),
                    ("edit_memo", "Edited Memo"),
                    ("submit_memo", "Submitted Memo"),
                    ("approve_memo", "Approved Memo"),
                    ("reject_memo", "Rejected Memo"),
                    ("cancel_memo", "Cancelled Memo"),
                    ("view_memo", "Viewed Memo"),
                    ("add_new_blog", "Added New Blog"),
                    ("edit_blog", "Edited Blog"),
                    ("save_as_draft", "Saved Blog as Draft"),
                    ("delete_blog", "Deleted Blog"),
                    ("permanently_delete_blog", "Permanently Deleted Blog"),
                    ("restore_blog", "Restored Blog"),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
    ]
