# Generated by Django 5.1.2 on 2026-01-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_alter_auditlog_audit_module_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="audit_type",
            field=models.CharField(
                choices=[
                    ("admin_login", "Admin Login"),
                    ("user", "User"),
                    ("deactivate_user", "Deactivated User"),
                    ("approve_user", "Approved User"),
                    ("restrict_user", "Restricted User"),
                    ("unrestrict_user", "Unrestricted User"),
                    ("remove_admin_user", "Removed Admin User"),
                    ("update_admin_user", "Updated Admin User"),
                    ("manual_debit_user", "Manually Debited User"),
                    ("manual_credit_user", "Manually Credited User"),
                    ("convert_user_type", "Converted User Type"),
                    ("view_correspondence", "Viewed Correspondence"),
                    ("change_correspondence_status", "Changed Correspondence Status"),
                    ("archive_correspondence", "Archived Correspondence"),
                    ("create_appraisal_template", "Created Appraisal Template"),
                    ("update_appraisal_template", "Updated Appraisal Template"),
                    ("archive_appraisal_template", "Archived Appraisal Template"),
                    ("delete_appraisal_template", "Deleted Appraisal Template"),
                    ("create_leave_type", "Created Leave Type"),
                    ("update_leave_type", "Updated Leave Type"),
                    ("delete_leave_type", "Deleted Leave Type"),
                    ("create_public_holiday", "Created Public Holiday"),
                    ("update_public_holiday", "Updated Public Holiday"),
                    ("delete_public_holiday", "Deleted Public Holiday"),
                    ("update_attendance_policy", "Updated Attendance Policy"),
                    ("create_leave_workflow", "Created Leave Approval Workflow"),
                    ("update_leave_workflow", "Updated Leave Approval Workflow"),
                    ("delete_leave_workflow", "Deleted Leave Approval Workflow"),
                    ("activate_leave_workflow", "Activated Leave Approval Workflow"),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
    ]
