# Generated by Django 5.1.2 on 2026-02-04 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_alter_auditlog_audit_module_and_more"),
        ("correspondence", "0021_correspondence_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="correspondence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="correspondence.correspondence",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="audit_type",
            field=models.CharField(
                choices=[
                    ("admin_login", "Admin Login"),
                    ("user", "User"),
                    ("deactivate_user", "Deactivated User"),
                    ("approve_user", "Approved User"),
                    ("restrict_user", "Restricted User"),
                    ("unrestrict_user", "Unrestricted User"),
                    ("remove_admin_user", "Removed Admin User"),
                    ("update_admin_user", "Updated Admin User"),
                    ("manual_debit_user", "Manually Debited User"),
                    ("manual_credit_user", "Manually Credited User"),
                    ("convert_user_type", "Converted User Type"),
                    ("change_correspondence_status", "Changed Correspondence Status"),
                    ("archive_correspondence", "Archived Correspondence"),
                    ("create_appraisal_template", "Created Appraisal Template"),
                    ("update_appraisal_template", "Updated Appraisal Template"),
                    ("archive_appraisal_template", "Archived Appraisal Template"),
                    ("delete_appraisal_template", "Deleted Appraisal Template"),
                    ("create_leave_type", "Created Leave Type"),
                    ("update_leave_type", "Updated Leave Type"),
                    ("delete_leave_type", "Deleted Leave Type"),
                    ("create_public_holiday", "Created Public Holiday"),
                    ("update_public_holiday", "Updated Public Holiday"),
                    ("delete_public_holiday", "Deleted Public Holiday"),
                    ("update_attendance_policy", "Updated Attendance Policy"),
                    ("create_leave_workflow", "Created Leave Approval Workflow"),
                    ("update_leave_workflow", "Updated Leave Approval Workflow"),
                    ("delete_leave_workflow", "Deleted Leave Approval Workflow"),
                    ("activate_leave_workflow", "Activated Leave Approval Workflow"),
                    ("create_task", "Created Task"),
                    ("update_task", "Updated Task"),
                    ("delete_task", "Deleted Task"),
                    ("assign_task", "Assigned Task"),
                    ("create_correspondence", "Created Correspondence"),
                    ("update_correspondence", "Updated Correspondence"),
                    ("delete_correspondence", "Deleted Correspondence"),
                    ("view_correspondence", "Viewed Correspondence"),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
    ]
