# Generated by Django 5.1.2 on 2026-01-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="reference_number",
            field=models.CharField(default=100, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="correspondence",
            name="sender",
            field=models.CharField(default="sender", max_length=255),
            preserve_default=False,
        ),
    ]
