# Generated by Django 5.1.2 on 2026-01-12 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0002_correspondence_reference_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="correspondence",
            name="assigned_by",
        ),
        migrations.RemoveField(
            model_name="correspondence",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="correspondence",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_correspondences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="through",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copied_correspondences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_correspondences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
