# Generated by Django 5.1.2 on 2026-01-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0003_remove_correspondence_assigned_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("finance", "Finance"),
                    ("HR", "Human Resources"),
                    ("project", "Project"),
                    ("logistics", "Logistics"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="is_confidential",
            field=models.BooleanField(default=False),
        ),
    ]
