# Generated by Django 5.1.2 on 2026-01-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0004_correspondence_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correspondence",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_action", "Pending MD Action"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
