# Generated by Django 5.1.2 on 2026-01-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0005_alter_correspondence_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="daily_serial",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="external_sender",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="serial_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_action", "Pending_Needs_Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
