# Generated by Django 5.1.2 on 2026-01-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0006_correspondence_daily_serial_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correspondence",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_action", "Pending_Needs_Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                    ("closed", "Closed"),
                ],
                default=None,
                max_length=20,
            ),
        ),
    ]
