# Generated by Django 5.1.2 on 2026-01-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0009_alter_correspondence_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correspondence",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_action", "Pending_Needs_Approval"),
                    ("new", "New"),
                    ("read", "Read"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
