# Generated by Django 5.1.2 on 2026-01-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0010_alter_correspondence_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
