# Generated by Django 5.1.2 on 2026-01-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0011_correspondence_archived_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="type",
            field=models.CharField(
                choices=[("internal", "Internal"), ("external", "External")],
                default="internal",
                max_length=20,
            ),
        ),
    ]
