# Generated by Django 5.1.2 on 2026-01-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0012_correspondence_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="image",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="md_note",
            field=models.TextField(blank=True),
        ),
    ]
