# Generated by Django 5.1.2 on 2026-01-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0015_alter_correspondence_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="correspondence",
            name="image",
        ),
        migrations.AddField(
            model_name="correspondence",
            name="image_urls",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_action", "Pending_Needs_Approval"),
                    ("new", "New"),
                    ("draft", "Draft"),
                    ("read", "Read"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
