# Generated by Django 5.1.2 on 2026-02-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0018_correspondence_delegated_to"),
    ]

    operations = [
        migrations.RenameField(
            model_name="correspondence",
            old_name="delegated_to",
            new_name="delegated_by",
        ),
    ]
