# Generated by Django 5.1.2 on 2026-02-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0019_rename_delegated_to_correspondence_delegated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correspondence",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_action", "Pending_Needs_Approval"),
                    ("new", "New"),
                    ("draft", "Draft"),
                    ("read", "Read"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                    ("closed", "Closed"),
                    ("replied", "Replied"),
                    ("forwarded", "Forwarded"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
