# Generated by Django 5.1.2 on 2026-02-03 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0020_alter_correspondence_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="correspondence.correspondence",
            ),
        ),
    ]
