# Generated by Django 5.1.2 on 2026-02-04 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0021_correspondence_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="forward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forwards",
                to="correspondence.correspondence",
            ),
        ),
    ]
