# Generated by Django 5.1.2 on 2026-02-04 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0022_correspondence_forward"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="correspondence",
            name="forward",
        ),
    ]
